version: 2
jobs:
  deploy:
    docker:
      - image: boiyaa/google-cloud-sdk-nodejs:9
        environment:
          STORAGE_BUCKET: ssanalysis
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup deps
          command: apt-get install -qq -y gettext
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GOOGLE_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project subreddit-sentiment-analysis
            gcloud --quiet config set compute/zone europe-west2-a
      - run:
          name: Token replace
          command: |
            envsubst < ./.circleci/.env.placeholder > .env
      - run:
          name: Install
          command: npm i
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: |
            gsutil defacl ch -u AllUsers:READER gs://$STORAGE_BUCKET
            gsutil rsync -R ./build gs://$STORAGE_BUCKET
            gsutil setmeta -h "Cache-Control:private, max-age=0, no-transform" gs://$STORAGE_BUCKET/*.js

workflows:
  version: 2
  release:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
